# GoofBall Cobblemon - standaard serverinstellingen.
# Alles wat hier niet staat krijgt de normale Minecraft-standaardwaarde.
# Na de eerste start vult Minecraft dit bestand zelf aan.
motd=§6GoofBall §aCobblemon
difficulty=normal
max-players=20
view-distance=10
simulation-distance=8
spawn-protection=0
online-mode=true
