name = "GoofBall Cobblemon"
author = "JustAGoofBall"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc4b6cc3adc8153fb762459b5188b6768521603c7242c30d5c6c712b13af0386"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
