name = "GoofBall Cobblemon"
author = "JustAGoofBall"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3922df6d060e1bd072ede4798502c189be0dccfed1c8781275dbfdca134a4206"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
