name = "GoofBall Cobblemon"
author = "JustAGoofBall"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9eb26f421a58029b20df3b1ede253d129ff25122a641a2a1f78cc0a4ae4bbe34"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
